JOSS paper setup
esa/polyhedral-gravity-model pull request #7
Opened 2023-07-03 03:07 UTC by gomezzz

Adding initial files for the JOSS submission

2023-08-11 07:53 UTC, gomezzz commented
@schuhmaj can we merge this? :) #9 builds on it, I think

2023-08-13 15:42 UTC, schuhmaj requested changes
Is the citation correct? Otherwise fine. 

Anyway, Many thanks for setting this up 👍😀

2023-08-13 15:42 UTC, schuhmaj commented on paper/paper.bib
> +@inproceedings{marak2023trajectory,
Isn't it the other way around?
Rasmus' paper in
Proceedings of the 9th International Conference on Astrodynamics Tools and Techniques, ICATT
And mine in
Proceedings of the 12th International Conference on Guidance, Navigation \& Control Systems (GNC)

2023-08-14 09:04 UTC, schuhmaj approved these changes
All good.

2023-08-14 09:19 UTC, merged